CREATE TABLE Categories 
(CategoryID STRING,
CategoryName STRING,
Description STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/hive/Categories.csv' INTO TABLE Categories;

CREATE TABLE Customers 
(CustomerID STRING,
CustomerName STRING,
ContactName	 STRING,
Address STRING,
City STRING,
PostalCode STRING,
Country STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/hive/Customers.csv' INTO TABLE Customers;

CREATE TABLE Orders 
(OrderID STRING,
CustomerID STRING,
EmployeeID	 STRING,
OrderDate STRING,
ShipperID STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/hive/Orders.csv' INTO TABLE Orders;

CREATE TABLE Employees 
(EmployeeID STRING,
LastName STRING,
FirstName STRING,
BirthDate STRING,
Photo STRING,
Notes STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/hive/Employees.csv' INTO TABLE Employees;

CREATE TABLE OrderDetails 
(OrderDetailID STRING,
OrderID STRING,
ProductID	 STRING,
Quantity STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/hive/OrderDetails.csv' INTO TABLE OrderDetails;

CREATE TABLE Products 
(ProductID STRING,
ProductName STRING,
SupplierID	 STRING,
Unit STRING,
Price STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/hive/Products.csv' INTO TABLE Products;

CREATE TABLE Shippers 
(ShipperID STRING,
ShipperName STRING,
Phone	 STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/hive/Shippers.csv' INTO TABLE Shippers;

CREATE TABLE Suppliers 
(SupplierID STRING,
SupplierName STRING,
ContactName	 STRING,
Address STRING,
City STRING,
PostalCode STRING,
Country STRING,
Phone STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA INPATH '/hive/Suppliers.csv' INTO TABLE Suppliers;